name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      APP_ENV: test
      TZ: 'Asia/Tokyo'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run RSpec
        run: bundle exec rspec --tag ~type:selenium
